"""add weather_snapshot table

Revision ID: 2f018befb7df
Revises: bd48b4896783
Create Date: 2026-06-20 14:09:00.642965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f018befb7df'
down_revision: Union[str, Sequence[str], None] = 'bd48b4896783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('humidity_pct', sa.SmallInteger(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_snapshot')
    # ### end Alembic commands ###
