"""add estimated_minutes to task

Revision ID: bd48b4896783
Revises: 8db9d52f19ce
Create Date: 2026-06-20 14:06:43.467917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd48b4896783'
down_revision: Union[str, Sequence[str], None] = '8db9d52f19ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'estimated_minutes')
    # ### end Alembic commands ###
